skipCreatedBefore: "2019-01-01"
comment: >
  Thanks for your contribution.
  

  PRISM Break development happens on GitLab at
  <https://gitlab.com/prism-break/prism-break>. Please re-open your ticket there.
  

  If you don't want to sign up for a GitLab account, you can send an email to
  <incoming+prism-break/prism-break@incoming.gitlab.com>. Emails end up on the
  issue tracker, you will receive replies and will be able to follow up. By
  default, visibility is restricted to [members][] only. Unless it's spam or
  sensitive (see below), it will be made public.


  If you can't sign up (common if you are using Tor), please drop a line at
  aforementioned email address, stating that you want a GitLab account and
  username that you want to claim. We'll sign up for you and send back account
  credentials with a temporary password. Support requests, and code of conduct
  violation reports are not made public.


  [members]: https://gitlab.com/groups/prism-break/-/group_members
